# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libglpk-dev
  - sudo apt-get install -y libglpk40

language: R
sudo: false
cache: packages
warnings_are_errors: false
